### ISSUE TITLE
WDC - REST API basic authentication not working

### ISSUE THREAD

**Issue by mittulmadaan** [tableau/webdataconnector#160]
Hi Team,
 
I am trying to connect to a REST API (web api), which requires basic authentication, with the web data connector (tableauwdc-2.1.latest.js).
 
REST API has WWW-Authenticate | Basic realm='public', basic authentication implemented. I have integrated REST API authentication module with WDC.
 
I am able to get basic authentication pop-up on all the browser. However, I am not able to get REST API basic authentication pop-up in WDC browser (in Tableau desktop). Any idea how to get this pop-up in WDC browser?

The credentials are working in basic authentication pop-up of browser, but not working in tableau desktop.

Would this basic authentication pop-up work on Tableau server? Can someone please let me know the possible workaround for this problem?

[https://community.tableau.com/message/590051?et=watches.email.thread#590051](Tableau Community post)

Thanks,
Mittul

**Comment by k504866430** [comment]
As an alternative, you can capture the username, password and then construct the 'Authorization' header in javascript ajax request. for e.g
```js
fetch(url, {
  method: 'GET',
  headers: {'Authorization' : btoa($('#username').value + ":" + $('#password').value)}
});
```

**Comment by Gokulame** [comment]
Hi All,

I am using Tableau 10.1 and got new requirnment to connect REST API and build Data source in tableau. But I am completely new with Web Data Connector. Could you please help me how to start and where to start. My email ID: gokula.m.e@ge.com and ph:95 38 48 19 19.

Thanks and Regards,
Gokula M E

**Comment by lbrendanl** [comment]
@mittulmadaan, unfortunately, the web browser that we use internally in Tableau does not support the automatic prompt.  Please use @k504866430's suggestion of constructing the authorization header.  

You can retrieve the username and password from your own custom form that you present to the user.

We do have plans to upgrade the browser we use in Tableau (QT WebKit), to a more modern chromium based browser (QT WebEngine).  I'll leave this issue open until that time for tracking purposes.

**Comment by recnaleerf** [comment]
It's now May, is this upgrade happening? I'm running into a similar issue which is also causing me to not be able to pass data with tableau.connectionData

**Comment by Shantam2** [comment]
Any update on this issue ?

**Comment by larryboymi** [comment]
How long will this stay unresolved?

**Comment by KeshiaRose** [comment]
This is something we are actively working on and it is the number one priority for the team working on WDC. However, the upgrade is not a quick fix as it is integrated other aspects of the product and will take a while to complete and test. Should come in 2019.

**Comment by wired00** [comment]
Is this still being looked at? by "actively working on and it is the number one priority for the team" it doesn't seem so high priority!

**Comment by seanmakesgames** [comment]
Hey @wired00 -- it absolutely is. For many reasons, this is a slow change and is very complex. We appreciate your patience as we work hard to get this out finally.

**Comment by sjwalsh83** [comment]
Is there any estimate as to timing on this change on the 2019 roadmap?

**Comment by closeit-tomf** [comment]
Hello, please is there any update on this issue? It is a problem also for our project - where we want the Tableau desktop to connect to OData source behind basic auth.
Thank you very much.

**Comment by illonage** [comment]
Hi all,

In Tableau 2019.4 and later, Web Data Connector uses Qt WebEngine, a Chromium-based browser. This change should solve this issue.

**Comment by illonage** [comment]
Hi all, 
I think we fixed in 2019.4. 

In Tableau 2019.4 and later, Web Data Connectors use Qt WebEngine, a Chromium-based browser. 
Can someone in this thread try it and confirm if it is fixed, please?

**Comment by closeit-tomf** [comment]
Hello,
the problem my company is facing is limited to OData connection with username/pass authentication (which is probably a subset of the issue related to web data connector as I believe OData connector in Tableau uses web data component as the underlying technology).

Tableau I am using:
2019.4.0 (20194.19.1010.1202) 64-bit, Professional Edition, trial

When I go to Connect - To a Server - More - OData and I fill the server URL & username/password, I believe the username/password is not correctly sent to the server. There is one captured HTTP request sent by Tableau:

`GET http://10.0.2.2:8080/api/OData.svc/ HTTP/1.1
Host: 10.0.2.2:8080
Accept: */*
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
User-Agent: Tableau Desktop 20194.19.1010.1202; pro; libcurl-client; 64-bit; en_US; Microsoft Windows 10 Pro (Build 18362);
Connection: Keep-Alive
`

I would expect to see http header with basic authorization in the request. Also, not sure if relevant, but the User-Agent indicates that libcurl-client is used, instead of Qt WebEngine?

The server I used works well in other BI tools (with OData with basic auth.)

Thank you very much for your time & help.

**Comment by illonage** [comment]
Hi @closeit-tomf,

The issue is not related to the issue you are facing.  The OData connector doesn't support browsing OData service documents.  You can vote for the idea here: https://community.tableau.com/ideas/8804

**Comment by daobuzhi** [comment]
@illonage 
I tested in 2019.4.3 (20194.20.0125.0835) 64-bit. 
The issue is still there. 

Here is my codes: 
    myConnector.init = function(initCallback){
        tableau.authType = tableau.authTypeEnum.basic;
        .....
        initCallback();
   }

myConnector.getSchema = async function (schemaCallback) {
     let xhr = new XMLHttpRequest();
     xhr.open("GET", `<url>`, true);
     xhr.withCredentials = true;
     //xhr.setRequestHeader("Authorization", 'Basic ' + btoa(username+':'+passcode));
  ......
}

It works fine in the Simulator (Chrome 83 dev), and can connect to target successfully when uncommenting setRequestHeader("Authorization).  But when trying to create WDC in Tableau, it prompts "Missing Password" with error code: 37CE01A3

Thank you for any suggestions.

**Comment by vinczemarton** [comment]
Hi people why is this issue closed? The issue is still present in 2020.3. The Tableau desktop behavior directly contradicts the documentation:

https://tableau.github.io/webdataconnector/docs/wdc_authentication

The only mention of basic authentication is that this dialog will pop up:
https://tableau.github.io/webdataconnector/assets/wdc_basic_auth.png

It does not pop up. It would help if there would be any example showing how basic authentication should be used.

Maybe I'm misreading the documentation, in that case suggest me the preferred auth type for my use case:

My use case would be to use a webdataconnector that works in both tableau desktop and tableau server.
My endpoints are:
* api/login -> provide username and password, it returns a token and some metadata
* api/data -> returns data if you include the correct token in the header

Can someone point me to an example where this flow is supported? Auth type should be "basic" as "custom" will not work with tableau server if I want user and password to be configured on tableau server, right?

**Comment by KeshiaRose** [comment]
Hi @vinczemarton, I just made a sample to show how this works. The sample only uses an API key as the password but the process is the same for username & password. The idea is that you would ask the user for their username and password in your own text boxes within the interactive phase (when the dialog window is open). You then store this information in tableau.username and tableau.password. While the workbook is open, the password will remain but once it is closed it is no longer saved. The next time the workbook is opened and the user wants to access/refresh the data it will prompt for username and password (as seen in the docs you mentioned). The prompt **only** occurs after the connection has already been configured and the password has been lost (from closing Tableau). (Note: the password can be embedded if published to Tableau Server/Online for future automated refreshes) Here is a [screen capture](https://user-images.githubusercontent.com/19785852/121627505-4fbb9f80-ca2c-11eb-94e0-fe0659a59fe2.mp4) of the sample and you can find the code [here](https://glitch.com/edit/#!/ticketmaster-events-wdc?path=README.md).

-Keshia

**Comment by vinczemarton** [comment]
Thanks for this example, it looks clear how can I create a custom interface to prompt in Tableau Desktop

> (Note: the password can be embedded if published to Tableau Server/Online for future automated refreshes)

This is the question: How? Do you need to modify your connector in any way?

Would the connector example that you shared work with Tableau Server?

At the end I would like to publish a connector that an other party can connect to, by both the Desktop and Server version of Tableau without my intervention.

**Comment by KeshiaRose** [comment]
No need to modify the WDC as long as you are using tableau.password to store the password. It's just an option when you are publishing to Server. 
![image](https://user-images.githubusercontent.com/19785852/122091014-39f80280-cdbd-11eb-9ccd-4eb6361e2b8f.png)
