### ISSUE TITLE
Tableau could not connect to the data source, Missing password

### ISSUE THREAD

**Issue by kennyshittu** [tableau/webdataconnector#343]
Please we're having  a weird issue with our web data-connector when testing with the latest version of Tableau public, I get the error below after the getSchema phase is completed and getData is called.

    An error occurred while communicating with Web Data Connector.

    Bad Connection: Tableau could not connect to the data source.
    Error Code: 37CE01A3
    Missing password.

I've confirmed that in our data-connector `tableau.password` is being set correctly, So I don't understand why this error is thrown intermittently .

See related issue here https://github.com/tableau-mkt/github-data-connector/issues/18

**Comment by illonage** [comment]
Hi @andela-Kshittu 
This issue is on our radar, I opened an issue here:https://github.com/tableau/webdataconnector/issues/337 

Thanks,
Gigi

**Comment by shawnxusy** [comment]
@illonage can we please get an update on this? This is making WDC not usable and impacting all of our customers.
I have attempted to put all creds info in connectionData but yields the same error.

The error "Missing password" is not helpful at all, what exact password is missing, even after moving things out of tableau.password?

**Comment by firefly707** [comment]
Hi @illonage, I'm a PM at Ascend.io.

Is there an ETA on when this will be resolved?  Right now we have several customers who are not able to connect to and use Tableau with our platform.  

Appreciate any update or guidance, 
Cheers!

**Comment by illonage** [comment]
Hi all - Great news! The fix should be the maintenance releases: 2019.4.5, 2020.1.1

**Comment by firefly707** [comment]
Thanks for the update Geraldine.

**Comment by brettandersonddw** [comment]
@illonage Do you know when those maintenance releases will go out?  We've had a lot of frustration from our platform's users lately regarding the WDC 'missing password' problem and are eagerly awaiting a resolution.  I didn't see anything about those releases at https://www.tableau.com/support/releases

**Comment by illonage** [comment]
Hi @brettandersonddw - these maintenance releases should be released in the next weeks. I will update you in this thread when it is released. Thank you for your patience

**Comment by illonage** [comment]
Hi All,
We just released the maintenance releases: https://www.tableau.com/support/releases/server

Can you try it and let me know if it is working :)

**Comment by Rishitha7** [comment]
I still get the same error message

**Comment by brettandersonddw** [comment]
@illonage it looks like you provided the incorrect link (download for Tableau Server).  After installing Tableau Desktop and Tableau Public 2020.1.2, it is working as expected now.

**Comment by illonage** [comment]
@Rishitha7 are you using Dekstop 2020.1.2? 
For downloading Desktop, the right link is: https://www.tableau.com/support/releases/desktop/2020.1.2

Thanks, @brettandersonddw for raising it up

**Comment by daobuzhi** [comment]
@illonage 
sorry to post again. I tracked #160, and guess it is the same as this one. I tested the latest version, 2020.1.2 (both Desktop pro and public as mentioned by @brettandersonddw ), and the issue is still there.  

Here is my codes: 

myConnector.init = function(initCallback){
tableau.authType = tableau.authTypeEnum.basic;
.....
initCallback();
}

myConnector.getSchema = async function (schemaCallback) {
let xhr = new XMLHttpRequest();
xhr.open("GET", <url>, true);
xhr.withCredentials = true;
//xhr.setRequestHeader("Authorization", 'Basic ' + btoa(username+':'+passcode));
......
}

It works fine in the Simulator (Chrome 83 dev), and can connect to target successfully when uncommenting setRequestHeader("Authorization). But when trying to create WDC in Tableau, it prompts "Missing Password" with error code: 37CE01A3

Thank you for any suggestions.

**Comment by illonage** [comment]
Hi @daobuzhi - I don't think that the issue you are facing is linked to this bug. Be sure when passing data between phases to use tableau.connectionData property. For more information, please read the documentation here: https://tableau.github.io/webdataconnector/docs/wdc_phases.html

Thanks,

**Comment by Rishitha7** [comment]
Thankyou so much everyone.
Sure I will look into it.

**Comment by daobuzhi** [comment]
Hi @illonage Thank you very much for the reply. 

Yes, we use tableau.connectionData to pass data between init and other phases. Now the issue is the basic authentication dialog does not shown, and tableau.username and tableau.password is empty. 

(the codes in the post, we tried passing in username and password in url,  and then via connectionData beween phases of cause). 

Is there any way to debug or log the authentication process ? 

Thank you!

**Comment by devstein** [comment]
> Now the issue is the basic authentication dialog does not shown, and tableau.username and tableau.password is empty.

We are also facing this on the latest Tableau Desktop and WDC. Any help is appreciated!

**Comment by illonage** [comment]
Hi @daobuzhi & @devstein - can you share the link to your WDC please?

**Comment by devstein** [comment]
@illonage I can't share the link, but what code of the connector do you want to want to see? What should trigger Tableau Desktop to prompt for the username and password? 

My init function is simple: 

```js
myConnector.init = function(initCallback){
tableau.authType = tableau.authTypeEnum.basic;

initCallback();
}
```

**Comment by illonage** [comment]
Hi @devstein - Was your code working before? If yes, in which version? If it is easier email me: gzanolli@tableau.com. Can you also confirm which version of Tableau Desktop are you using now?

**Comment by devstein** [comment]
@illonage I'm using Tableau Desktop 2020.1. I haven't tried on an earlier version of Tableau Desktop, so I can't say if it worked before. 

My workaround was switching the `authType` to `custom` and implementing a simple login form to authenticate the user rather than relying on the built-in basic auth form.

**Comment by danrod43** [comment]
@devstein can you please share your simple login form to authenticate? I'm having the same issue

**Comment by illonage** [comment]
@danrod43 can you share ur code, please? So I can have look

**Comment by danrod43** [comment]
@illonage I am stuck trying to implement OAuth authentication into the code below. I think there's also another file I need to save that stores the clientID and secret.

(function() {
    // Create the connector object
    var myConnector = tableau.makeConnector();
	
 //Danny's adding of authentication
	 myConnector.init = function(initCallback) {
      tableau.authType = tableau.authTypeEnum.basic;
      initCallback(); 
  }  
    // Define the schema
    myConnector.getSchema = function(schemaCallback) {
        var cols = [{				
			id: "number",
			alias: "number_alias",
            dataType: tableau.dataTypeEnum.string
        }, {
            id: "sys_created_by",
            alias: "User_Created",
            dataType: tableau.dataTypeEnum.string
        }];

        var tableSchema = {
            id: "sNOW",
            alias: "Call Data",
            columns: cols
        };

        schemaCallback([tableSchema]);
    };

    // Download the data
    myConnector.getData = function(table, doneCallback) {
        $.getJSON("link to URL with json file", function(resp) {
            var feat = resp.result,
                tableData = [];

            // Iterate over the JSON object
            for (var i = 0, len = feat.length; i < len; i++) {
                tableData.push({
					//"id": feat[i] ["id"],
                    "number": feat[i].number,
                    "sys_created_by": feat[i].sys_created_by

                });
            } 

            table.appendRows(tableData);
            doneCallback();
        });
    };

    tableau.registerConnector(myConnector);

    // Create event listeners for when the user submits the form
    $(document).ready(function() {
        $("#submitButton").click(function() {
            tableau.connectionName = "sNOW Calls Feed"; // This will be the data source name in Tableau
            tableau.submit(); // This sends the connector object to Tableau
        });
    });
})();
